### ISSUE TITLE
Big brother is watching you

### ISSUE THREAD

**Issue by alexey-hw** [slawiko/remindmelater_bot#1]
Хороший бот и токены интересные
[а тя- тя](https://github.com/slawiko/remindmelater_bot/blob/develop/app.py#L9)

**Comment by slawiko** [comment]
@alexey-hw вы должны были сказать что-то типа "вон из профессии". Однако, важно заметить, что токен я уже сменил. Да да, не тут-то было, Алексея. Считаю можно закрывать
